// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SynEx
{
    internal sealed partial class Vsix
    {
        public const string Id = "SynEx.070df596-5524-4fef-be58-904341eeea24";
        public const string Name = "SynEx";
        public const string Description = @"Syntax Extractor Helps you Extract your code.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Josef Nobach";
        public const string Tags = "";
    }
}
