// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SynEx
{
    internal sealed partial class Vsix
    {
        public const string Id = "SynEx.070df596-5524-4fef-be58-904341eeea24";
        public const string Name = "SynEx";
        public const string Description = @"Syntax Extractor: Enhance Your AI-Code Interaction

Syntax Extractor is a versatile Visual Studio extension designed to transform your code into a syntax tree for seamless communication with AI platforms like ChatGPT. It offers customizable extraction types, smart output management, and clipboard convenience.

Key Features:

Intuitive integration with Visual Studio
Customizable extraction: function names, parameters, return types, and access modifiers
Syntax tree saved outside the main solution folder
Automatic code copy to clipboardSyntax Extractor: Enhance Your AI-Code Interaction

Syntax Extractor is a versatile Visual Studio extension designed to transform your code into a syntax tree for seamless communication with AI platforms like ChatGPT. It offers customizable extraction types, smart output management, and clipboard convenience.

Key Features:

Intuitive integration with Visual Studio
Customizable extraction: function names, parameters, return types, and access modifiers
Syntax tree saved outside the main solution folder
Automatic code copy to clipboardExtraction Types:

Function Names: Retrieve only the names of functions within your code.
Function Names & Parameters: Extract function names along with their respective parameters.
Function Names, Parameters & Return Types: Obtain function names, parameters, and their return types for a comprehensive overview.
Access Modifier, Static, Function Names, Parameters & Return Types: Get the full scope with access modifiers, static information, function names, parameters, and return types.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Josef Nobach";
        public const string Tags = "";
    }
}
