// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SynEx
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SynExString = "d309f791-903f-11d0-9efc-00a0c911004f";
        public static Guid SynEx = new Guid(SynExString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int IDM_VS_MENU_EXTENSIONS = 0x0091;
        public const int MyMenuGroup = 0x0001;
        public const int MyCommand = 0x0100;
    }
}